export default {
  UI: {
    start_game: 'Start Game',
    join_game: 'Join Game',
    create_room: 'Create Room',
    ready: 'Ready',
    leave: 'Leave',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    settings: 'Settings',
    inventory: 'Inventory',
    map: 'Map',
    help: 'Help',
    respawn: 'Respawn',
    resume: 'Resume',
    controls: 'Controls',
    volume: 'Volume',
    color_blind: 'Color-Blind Mode',
    difficulty: 'Difficulty',
    easy: 'Easy',
    normal: 'Normal',
    hard: 'Hard',
    master_volume: 'Master Volume',
    player_name: 'Player Name',
    select_role: 'Select Role',
    room_code: 'Room Code',
  },
  CHAT: {
    global_prefix: '[Global]',
    team_prefix: '[Team]',
    system_prefix: '[System]',
    press_t: 'T: chat',
    press_tab: 'Tab: switch channel',
  },
  ROLES: {
    PM: 'Plant Maintenance',
    LO: 'Logistics Operator',
    RO: 'Reactor Operator',
  },
  TASKS: {
    REPAIR_PIPE: 'Repair pipe',
    REPAIR_PUMP: 'Fix coolant pump',
    REPAIR_TURBINE: 'Repair turbine',
    REPAIR_GENERATOR: 'Repair generator',
    DELIVER_FUEL: 'Deliver fuel rod',
    DELIVER_PART: 'Deliver spare part',
  },
  ERRORS: {
    room_full: 'Room is full',
    invalid_role: 'Invalid role',
    not_enough_fuel: 'Not enough fuel rods',
    machine_too_damaged: 'Machine too damaged to operate',
    wrong_tool: 'Wrong tool for this task',
    player_not_found: 'Player not found',
    invalid_command: 'Invalid admin command',
    already_ready: 'Already marked as ready',
    game_in_progress: 'Game already in progress',
    connection_lost: 'Connection lost. Reconnecting...',
    reconnect_failed: 'Failed to reconnect. Reload to try again.',
  },
  WARNINGS: {
    radiation_high: 'Radiation levels rising!',
    meltdown_imminent: 'MELTDOWN IMMINENT!',
    blackout_imminent: 'Blackout imminent — no power output!',
    pipe_burst: 'A pipe has burst!',
    turbine_overload: 'Turbine RPM exceeding safe limits!',
    reactor_overheat: 'Reactor core temperature critical!',
    coolant_low: 'Coolant levels dangerously low!',
  },
  SUCCESS: {
    repair_complete: 'Repair complete!',
    fuel_delivered: 'Fuel delivered!',
    part_delivered: 'Part delivered!',
    task_complete: 'Task completed!',
    reactor_stable: 'Reactor stabilized.',
    power_restored: 'Power restored.',
    game_started: 'Game has started. Good luck!',
    role_assigned: 'Role assigned.',
  },
  ADMIN: {
    server_started: 'Server started',
    player_kicked: 'Player kicked',
    player_banned: 'Player banned',
    game_reset: 'Game has been reset',
    broadcast_sent: 'Broadcast sent to all players',
  },
  TUTORIAL: {
    slide1_title: 'Plant Maintenance (PM)',
    slide1_desc: 'Repair broken machines using [E].\nKeep the plant running by fixing pipes,\npumps, turbines, and generators.',
    slide1_keybinds: 'WASD: Move | E: Interact/Repair',
    slide2_title: 'Logistics Operator (LO)',
    slide2_desc: 'Deliver fuel rods from storage\nto the reactor core using the crane.\nKeep the reactor fueled!',
    slide2_keybinds: 'Arrows: Move Crane | Click: Pick/Place | ESC: Exit',
    slide3_title: 'Reactor Operator (RO)',
    slide3_desc: 'Control the reactor from the\nControl Room. Adjust rods, pumps,\nand SCRAM in emergencies.',
    slide3_keybinds: 'Mouse: Sliders | Click: SCRAM | ESC: Exit',
    done: 'Got it!',
  },
  ACHIEVEMENTS: {
    meltdown_prevented: 'First Meltdown Prevented',
    meltdown_prevented_desc: 'SCRAM before heat reaches critical',
    mw_generated: '100 MW Generated',
    mw_generated_desc: 'Generate 100 total megawatts',
    perfect_shift: 'Perfect Shift',
    perfect_shift_desc: 'Complete a game with no failures',
    all_turbines: 'All Turbines Online',
    all_turbines_desc: 'Both turbines running simultaneously',
  },
  TOOLTIPS: {
    reactor: 'Reactor Core\nConverts fuel to heat.\nHeat: {heat}°C | Rods: {rods}%\nStatus: {status}',
    turbine: 'Turbine\nConverts steam to RPM.\nRPM: {rpm} | Pressure: {pressure}\nStatus: {status}',
    pump: 'Coolant Pump\nRemoves heat from reactor.\nSpeed: {speed}% | Coolant: {coolant}%\nStatus: {status}',
    generator: 'Generator\nConverts RPM to electricity.\nOutput: {mw} MW | RPM: {rpm}\nStatus: {status}',
    pipe: 'Steam Pipe\nCarries steam to turbines.\nPressure: {pressure} | Status: {status}',
    condenser: 'Condenser\nConverts exhaust steam to water.\nEfficiency: {efficiency}%\nStatus: {status}',
    control_rods: 'Control Rods\nInsertion: {level}%\nControls reaction rate.\nStatus: {status}',
  },
};
